### ISSUE TITLE
Chyba pri inicializácii dockera

### ISSUE THREAD

**Issue by dani46** [touch4it/mtaa-backend#1]
Win 10 Home 64bit  

$ docker-compose.exe up
Starting mtaabackendmaster_db_1 ... done
Starting mtaabackendmaster_node_1 ... done
Attaching to mtaabackendmaster_db_1, mtaabackendmaster_node_1
db_1    | The files belonging to this database system will be owned by user "postgres".
db_1    | This user must also own the server process.
db_1    |
db_1    | The database cluster will be initialized with locale "en_US.utf8".
db_1    | The default database encoding has accordingly been set to "UTF8".
db_1    | The default text search configuration will be set to "english".
db_1    |
db_1    | Data page checksums are disabled.
db_1    |
db_1    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1    | creating subdirectories ... ok
db_1    | selecting default max_connections ... 100
db_1    | selecting default shared_buffers ... 128MB
db_1    | selecting dynamic shared memory implementation ... posix
db_1    | creating configuration files ... ok
db_1    | running bootstrap script ... LOG:  could not link file "pg_xlog/xlogtemp.27" to "pg_xlog/000000010000000000000001": Operation not permitted
db_1    | FATAL:  could not open file "pg_xlog/000000010000000000000001": No such file or directory
db_1    | child process exited with exit code 1
db_1    | initdb: removing contents of data directory "/var/lib/postgresql/data"
mtaabackendmaster_db_1 exited with code 1
node_1  |
node_1  | > mtaa@0.1.0 start /app
node_1  | > npm install && node app.js
node_1  |
node_1  | npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
node_1  | npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
node_1  | npm ERR! path /app/node_modules/resolve
node_1  | npm ERR! code ENOENT
node_1  | npm ERR! errno -2
node_1  | npm ERR! syscall rename
node_1  | npm ERR! enoent ENOENT: no such file or directory, rename '/app/node_modules/resolve' -> '/app/node_modules/.resolve.DELETE'
node_1  | npm ERR! enoent This is related to npm not being able to find a file.
node_1  | npm ERR! enoent
node_1  |
node_1  | npm ERR! A complete log of this run can be found in:
node_1  | npm ERR!     /root/.npm/_logs/2018-03-06T13_35_52_220Z-debug.log
node_1  | npm ERR! code ELIFECYCLE
node_1  | npm ERR! errno 254
node_1  | npm ERR! mtaa@0.1.0 start: `npm install && node app.js`
node_1  | npm ERR! Exit status 254
node_1  | npm ERR!
node_1  | npm ERR! Failed at the mtaa@0.1.0 start script.
node_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
node_1  |
node_1  | npm ERR! A complete log of this run can be found in:
node_1  | npm ERR!     /root/.npm/_logs/2018-03-06T13_35_52_296Z-debug.log
mtaabackendmaster_node_1 exited with code 254

**Comment by vsulak** [comment]
bol este jeden commit, ktory prave toto mal riesit, ale za cenu ze `docker-compose down` zrusi databazu. Skus ci to uz ide ako ma

**Comment by royalko** [comment]
$ docker-compose up
Starting mtaabackend_db_1 ... done
Starting mtaabackend_node_1 ... done
Attaching to mtaabackend_db_1, mtaabackend_node_1
db_1    | LOG:  database system was shut down at 2018-03-06 17:00:40 UTC
db_1    | LOG:  MultiXact member wraparound protections are now enabled
db_1    | LOG:  database system is ready to accept connections
node_1  |
node_1  | > mtaa@0.1.0 start /app
node_1  | > npm install && node app.js
node_1  |
node_1  | npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do m
y best with it!
node_1  | npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do m
y best with it!
**node_1  | npm ERR! path /app/node_modules/sails/node_modules/anchor/node_modules/geojsonhint/node_modules/optimist/node_modules/wordwrap/package.json.1321756295**
node_1  | npm ERR! code ENOENT
node_1  | npm ERR! errno -2
node_1  | npm ERR! syscall open
**node_1  | npm ERR! enoent ENOENT: no such file or directory, open '/app/node_modules/sails/node_modules/anchor/node_modules/geojsonhint/node_modules/optimist/node_modules/wordwrap/package.json.1321756295'**
node_1  | npm ERR! enoent This is related to npm not being able to find a file.
node_1  | npm ERR! enoent
node_1  |
node_1  | npm ERR! A complete log of this run can be found in:
node_1  | npm ERR!     /root/.npm/_logs/2018-03-06T17_02_39_619Z-debug.log
node_1  | npm ERR! code ELIFECYCLE
node_1  | npm ERR! errno 254
node_1  | npm ERR! mtaa@0.1.0 start: `npm install && node app.js`
node_1  | npm ERR! Exit status 254
node_1  | npm ERR!
node_1  | npm ERR! Failed at the mtaa@0.1.0 start script.
node_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
node_1  |
node_1  | npm ERR! A complete log of this run can be found in:
node_1  | npm ERR!     /root/.npm/_logs/2018-03-06T17_02_40_060Z-debug.log
mtaabackend_node_1 exited with code 254

**Comment by vsulak** [comment]
@royalko skus teraz, pridal som ten balicek do dependencies

**Comment by royalko** [comment]
opat hodilo 254
https://pastebin.com/RFh4hJv9

**Comment by vsulak** [comment]
@royalko pridal som este dalsie dependencies z toho error logu .. ak by to ani tak nepomohlo, tak treba ist do `app/node_modules/sails/node_modules/anchor/node_modules/geojsonhint/node_modules/optimist` a manualne dat `npm install wordwrap`

**Comment by royalko** [comment]
@vsulak hodilo to znovu 254, tieto zlozky mi vobec nevytvorilo, ak som ich rucne vytvoril a v zlozke `app/node_modules/sails/node_modules/anchor/node_modules/geojsonhint/node_modules/optimist`
vyhodilo mi to tuto chybu
https://pastebin.com/74xhr4pK

**Comment by royalko** [comment]
@vsulak Tak uz som to asi rozbehal https://pastebin.com/VU0q58gn

**Comment by vsulak** [comment]
@royalko po tych poslednych pridanych dependencies?

**Comment by royalko** [comment]
@vsulak musel som stiahnut najprv node.js z ich stranky a potom v pricienku `app/node_modules` som zadal prikaz `npm install sails`

Ked ale dam do browseru  tak mi ju nenacita

//EDIT: ked upravis este port forwarding vo VM to uz pojde
