### ISSUE TITLE
[question] Generovanie kolekcie

### ISSUE THREAD

**Issue by ludko** [touch4it/mtaa-backend#2]
Da sa kolekcia nejakym sposobom vygenerovat zo Sails modelu, pripadne opacne z kolekcie model, alebo si **mtaa.postman_collection.json** vytvoril zvlast v Postmane a sem iba spristupnil?

**Comment by vsulak** [comment]
Postman a Sails su oddelene entity, takze nie, negeneruje sa jedno z druheho
