### ISSUE TITLE
Názov tabulky?

### ISSUE THREAD

**Issue by janpetras123** [touch4it/mtaa-backend#3]
Ahoj, keď chcem dať do mtaa-backend/db/init súbor .sql, a napíšem do neho:

INSERT INTO <nazov_tabulky>(meno, priezvisko, datum_narodenia, vaha) VALUES
('Louis', 'Fox', '1989-03-21', '51'),
('Rose', 'Torres', '1988-12-15', '45');

tak to vyhlási, že je chyba na <nazov_tabulky>.
Čo dať na miesto <nazov_tabulky>? Skúšal som item, items, mtaa, mtaadb... a neviem na to prísť.

**Comment by vsulak** [comment]
v init sql subore treba najprv dat create tabulky, potom az insert. A potom ak je syntax spravny to musi fungovat

**Comment by janpetras123** [comment]
Vieš poslať príklad, prosím ťa?

**Comment by vsulak** [comment]
[mysql-dump.sql.txt](https://github.com/touch4it/mtaa-backend/files/1790349/mysql-dump.sql.txt)
[psql-dump.sql.txt](https://github.com/touch4it/mtaa-backend/files/1790350/psql-dump.sql.txt)
