### ISSUE TITLE
ItemController.find

### ISSUE THREAD

**Issue by janpetras123** [touch4it/mtaa-backend#4]
Ahoj, keď zavolám GET /item/, tak chcem vrátiť všetky objekty, ktoré tam sú (čo sa aj vykoná), ale zároveň, aby sa o každom objekte nevracali všetky údaje, ale len niektoré, pevne vybrané. Napríklad:
Toto sú údaje, ktoré má každý záznam (potreba pri zobrazení jedného konkrétneho záznamu)
{
        "brand": "Audi",
        "type": "Q7",
        "state": 2,
        "kilometers": 120000,
        "power": 250,
        "torque": 210,
        "price": 22000,
        "picture": "audiq7.png"
}

ale pri zobrazení všetkých, ktoré tam sú potrebujem mať len

{
        "brand": "Audi",
        "price": 22000,
        "picture": "audiq7.png",
}

Ako sa to dá spraviť?

**Comment by vsulak** [comment]
spravit si vlastnu akciu v controlleri

https://sailsjs.com/documentation/concepts/controllers

https://stackoverflow.com/a/29769995/3628426

**Comment by janpetras123** [comment]
Mám vytvorený ListController.js, v ktorom mám:

module.exports = {

};

potom mám List.js v ktorom je:

module.exports = {
    attributes: {
        brand: {
            type: 'string',
            required: true
        },
        price: {
            type: 'float',
            required: true
        },
        picture: {
            type: 'string',
            required: true
        }
};

a v súbore routes.js je:

'get /cars': 'ListController.find'

lenže takto sa vytvorí nová tabuľka a to nechcem. Ja chcem čerpať údaje iba z tej jednej.

A dá sa v súbore routes.js vytvoriť niečo takéto:

'get /cars': 'ItemController.find({ select: ['brand', 'price', 'picture'])'

aby bol výstup len tie tri požadované atribúty?

**Comment by vsulak** [comment]
https://sailsjs.com/documentation/concepts/models-and-orm/model-settings#?tablename .. tymto si nasmerujes model na inu tabulku

to co ale ty chces je vytvorit si novu funkciu v ItemController, idealne nazvanu inak ako `find` / `findOne` ak nechces prist o povodne a potom si nasmerujes v routes cestu

**Comment by janpetras123** [comment]
Skúsim to.

Si dnes prípadne po 12-tej na fiitke?

**Comment by vsulak** [comment]
podarilo sa?

**Comment by janpetras123** [comment]
Nie, nepodarilo.

**Comment by j91321** [comment]
@janpetras123 povedzne, že toto je môj model v Item.js (skrátený)
```javascript
module.exports = {
  attributes: {
    title: {
      type: 'string',
      required: true
    },
    author: {
      type: 'string',
      required: true
    },
    published: {
      type: 'date',
      defaultsTo: '1970-01-01'
    }
 }
};
```
Chcem vytiahnúť len id, title a author. V ItemController.js do module.exports pridáš niečo takéto:
```javascript
findList: function (req, res) {
    Item.find({where: {}, select: ['id', 'title', 'author']}).exec(function(err, items) {
      if (err) {
        // handle the error
      } else {
        return res.send(items);
      }
    });

  }
```
a nakoniec do routes.js pridáš `'get /books2': 'ItemController.findList'` a na localhost:8080/books2 dostaneš (published chýba)
```json
[
  {
    "id": 1,
    "title": "1984",
    "author": "George Orwell"
  },
  {
    "id": 2,
    "title": "Roadside Picnic",
    "author": "Arkady Strugatsky"
  },
  {
    "id": 3,
    "title": "test book",
    "author": "Arkady Strugatsky"
  }
]
```

**Comment by janpetras123** [comment]
Ide to. Ďakujem pekne.
